"use client";

import { Download, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const stats = [["Total Users","2,486"],["Active Users","1,842"],["Total Workspaces","128"],["Active Workspaces","96"],["Projects","342"],["Tasks Completed","18,420"]];
const values = [32,46,40,58,64,60,78,88,82,96];
export function SystemAnalytics(){
  // TODO: Connect system analytics API
  return <div className="space-y-6"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight">System Analytics</h1><p className="mt-2 text-sm text-muted-foreground">Monitor platform-wide activity, users, workspaces and growth.</p></div><div className="flex flex-wrap gap-2"><select className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option>Last 30 days</option><option>Last quarter</option></select><select className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option>All workspaces</option><option>Business plan</option></select><Button variant="outline"><RefreshCw/>Refresh</Button><Button variant="outline"><Download/>Export</Button></div></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label,value])=><Card key={label} className="transition-shadow hover:shadow-md"><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-emerald-600 dark:text-emerald-400">↑ 12.4% from previous period</p></CardContent></Card>)}</div><div className="grid gap-4 xl:grid-cols-3"><Chart title="User Growth" copy="New and active users over time." className="xl:col-span-2"/><Chart title="Task Completion" copy="Completed tasks across all workspaces."/></div><div className="grid gap-4 lg:grid-cols-3"><Chart title="Workspace Growth" copy="New workspace creation."/><Distribution/><Chart title="Project Activity" copy="Projects with recent updates."/></div><Card><CardHeader><CardTitle>Recent system activity</CardTitle><CardDescription>A quick view of platform-wide events.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm">{["18 new users joined FlowDesk","4 workspaces upgraded to Business","126 tasks completed in the last hour"].map((item,index)=><div key={item} className="flex items-center justify-between border-b pb-3 last:border-0 last:pb-0"><span>{item}</span><span className="text-xs text-muted-foreground">{index + 1} hour ago</span></div>)}</CardContent></Card></div>;
}
function Chart({title,copy,className}:{title:string;copy:string;className?:string}){return <Card className={className}><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{copy}</CardDescription></CardHeader><CardContent><div className="flex h-48 items-end gap-2 pt-4">{values.map((value,index)=><div key={index} className="group relative flex-1 rounded-t bg-primary/75 transition-colors hover:bg-primary" style={{height:`${value}%`}}><span className="sr-only">{value}</span></div>)}</div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>Week 1</span><span>Week 4</span></div></CardContent></Card>}
function Distribution(){return <Card><CardHeader><CardTitle>Workspace Distribution</CardTitle><CardDescription>Plans across active workspaces.</CardDescription></CardHeader><CardContent className="space-y-4">{[["Business",62],["Free",28],["Enterprise",10]].map(([label,width])=><div key={String(label)}><div className="mb-1 flex justify-between text-sm"><span>{label}</span><span className="text-muted-foreground">{width}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${width}%`}}/></div></div>)}</CardContent></Card>}
