"use client";

import * as React from "react";
import { Copy, GripVertical, Plus, Trash2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { triggerOptions, type WorkflowStep } from "@/lib/workflows-data";

const fields = ["Status", "Priority", "Assignee", "Project", "Due date"];
const operators = ["is", "is not", "contains", "greater than", "less than"];
const values = ["Todo", "In Progress", "Done", "High", "Medium", "Low"];
const actions = ["Send notification", "Assign task", "Change task status", "Add comment", "Create task", "Update task", "Send email", "Add member", "Remove member"];

export function WorkflowBuilder({ trigger, onTriggerChange, steps, onStepsChange }: { trigger: string; onTriggerChange: (value: string) => void; steps: WorkflowStep[]; onStepsChange: (steps: WorkflowStep[]) => void }) {
  const [draggedId, setDraggedId] = React.useState<string | null>(null);
  const update = (id: string, changes: Partial<WorkflowStep>) => onStepsChange(steps.map((step) => step.id === id ? { ...step, ...changes } : step));
  const addStep = (kind: WorkflowStep["kind"]) => onStepsChange([...steps, kind === "condition" ? { id: crypto.randomUUID(), kind, title: "Check condition", field: "Priority", operator: "is", value: "High" } : { id: crypto.randomUUID(), kind, title: "Send notification", action: "Send notification", recipient: "Project team", message: "" }]);
  const reorder = (targetId: string) => { if (!draggedId || draggedId === targetId) return; const source = steps.find((step) => step.id === draggedId); if (!source) return; const without = steps.filter((step) => step.id !== draggedId); const index = without.findIndex((step) => step.id === targetId); onStepsChange([...without.slice(0, index), source, ...without.slice(index)]); setDraggedId(null); };
  return <div className="space-y-4"><Card className="border-primary/30"><CardContent className="p-4"><p className="text-xs font-semibold tracking-wider text-primary">WHEN</p><select value={trigger} onChange={(event) => onTriggerChange(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm font-medium"><option value="">Select a trigger</option>{triggerOptions.map((option) => <option key={option}>{option}</option>)}</select></CardContent></Card>
    {steps.map((step, index) => <React.Fragment key={step.id}><div className="mx-auto h-5 w-px bg-border" aria-hidden="true" /><Card draggable onDragStart={() => setDraggedId(step.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => reorder(step.id)} className={`transition-all ${draggedId === step.id ? "opacity-50" : ""}`}><CardContent className="p-4"><div className="flex items-start gap-2"><button type="button" aria-label="Drag to reorder" className="mt-1 cursor-grab touch-none text-muted-foreground active:cursor-grabbing"><GripVertical className="size-4" /></button><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold tracking-wider text-primary">{step.kind === "condition" ? "IF" : "THEN"}</p><div className="flex"><Button size="icon" variant="ghost" aria-label="Duplicate step" onClick={() => onStepsChange([...steps.slice(0, index + 1), { ...step, id: crypto.randomUUID() }, ...steps.slice(index + 1)])}><Copy /></Button><Button size="icon" variant="ghost" aria-label="Remove step" onClick={() => onStepsChange(steps.filter((item) => item.id !== step.id))}><Trash2 className="text-destructive" /></Button></div></div>{step.kind === "condition" ? <div className="mt-3 grid gap-2 sm:grid-cols-3"><select value={step.field} onChange={(event) => update(step.id, { field: event.target.value })} className="h-9 rounded-md border border-input bg-background px-2 text-sm">{fields.map((option) => <option key={option}>{option}</option>)}</select><select value={step.operator} onChange={(event) => update(step.id, { operator: event.target.value })} className="h-9 rounded-md border border-input bg-background px-2 text-sm">{operators.map((option) => <option key={option}>{option}</option>)}</select><select value={step.value} onChange={(event) => update(step.id, { value: event.target.value })} className="h-9 rounded-md border border-input bg-background px-2 text-sm">{values.map((option) => <option key={option}>{option}</option>)}</select></div> : <div className="mt-3 grid gap-2 sm:grid-cols-2"><select value={step.action} onChange={(event) => update(step.id, { action: event.target.value, title: event.target.value })} className="h-9 rounded-md border border-input bg-background px-2 text-sm sm:col-span-2">{actions.map((option) => <option key={option}>{option}</option>)}</select><Input value={step.recipient ?? ""} onChange={(event) => update(step.id, { recipient: event.target.value })} placeholder="Recipient" /><Input value={step.message ?? ""} onChange={(event) => update(step.id, { message: event.target.value })} placeholder="Message or configuration" /></div>}</div></div></CardContent></Card></React.Fragment>)}
    <div className="flex flex-wrap justify-center gap-2"><Button variant="outline" size="sm" onClick={() => addStep("condition")}><Plus />Add condition</Button><Button variant="outline" size="sm" onClick={() => addStep("action")}><Plus />Add action</Button></div>
  </div>;
}
