"use client";
import Link from "next/link";
import { BarChart3, CheckSquare, FileText, MoreHorizontal, Users, Workflow } from "lucide-react";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Card, CardContent } from "@/components/ui/card";
import { AgentStatusBadge } from "@/components/ai-agents/agent-status-badge";
import type { Agent } from "@/lib/ai-agents-data";

const icons = { chart: BarChart3, check: CheckSquare, users: Users, workflow: Workflow, report: FileText };
export function AgentCard({ agent, onToggle }: { agent: Agent; onToggle: (id: string) => void }) { const Icon = icons[agent.icon]; const active = agent.status === "active"; return <Card className="h-full min-h-64 transition-[box-shadow,border-color] hover:border-primary/25 hover:shadow-md"><CardContent className="flex h-full flex-col p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="size-5" /></div><div className="min-w-0"><Link href={`/ai-agents/${agent.id}`} className="line-clamp-1 font-semibold hover:text-primary">{agent.name}</Link><p className="mt-1 line-clamp-2 min-h-10 text-sm leading-5 text-muted-foreground">{agent.description}</p></div></div><DropdownMenu><DropdownMenuTrigger aria-label={`Actions for ${agent.name}`} className="rounded-md p-1 text-muted-foreground hover:bg-accent"><MoreHorizontal className="size-4" /></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>Duplicate</DropdownMenuItem><DropdownMenuItem variant="destructive">Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><div className="mt-5 flex items-center gap-3 text-xs text-muted-foreground"><AgentStatusBadge status={agent.status} /><span>{agent.actions} actions</span><span className="truncate">Last active {agent.lastActive}</span></div><div className="mt-auto flex items-center justify-between border-t pt-4"><span className="text-xs font-medium text-muted-foreground">{agent.type}</span><button type="button" role="switch" aria-checked={active} aria-label={`${active ? "Pause" : "Activate"} ${agent.name}`} onClick={() => onToggle(agent.id)} className={`relative inline-flex h-7 w-14 cursor-pointer items-center rounded-full border p-0.5 text-[10px] font-bold tracking-wide focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${active ? "border-primary bg-primary text-primary-foreground" : "border-border bg-muted text-muted-foreground"}`}><span className={`absolute ${active ? "left-2" : "right-2"}`}>{active ? "ON" : "OFF"}</span><span className={`size-5 rounded-full bg-background shadow-sm transition-transform duration-200 ${active ? "translate-x-7" : ""}`} /></button></div></CardContent></Card>; }
