"use client";
import * as React from "react";
import { Bot, Plus } from "lucide-react";
import { AgentCard } from "@/components/ai-agents/agent-card";
import { CreateAgentDialog } from "@/components/ai-agents/create-agent-dialog";
import { mockAgents, type Agent } from "@/lib/ai-agents-data";

export function AiAgentsPage() { const [agents, setAgents] = React.useState(mockAgents); const [open, setOpen] = React.useState(false); const toggle = (id: string) => { // TODO: Connect update-agent API
setAgents((current) => current.map((agent) => agent.id === id ? { ...agent, status: agent.status === "active" ? "paused" : "active" } : agent)); }; return <div className="flex flex-col gap-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Automation</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">AI Agents</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Create AI-powered assistants that can help your team with repetitive workspace tasks.</p></div><Button onClick={() => setOpen(true)}><Plus />Create agent</Button></header>{agents.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{agents.map((agent) => <AgentCard key={agent.id} agent={agent} onToggle={toggle} />)}</div> : <div className="flex min-h-72 flex-col items-center justify-center rounded-xl border border-dashed text-center"><Bot className="size-9 text-muted-foreground" /><h2 className="mt-4 text-lg font-semibold">No AI agents yet</h2><p className="mt-1 max-w-sm text-sm text-muted-foreground">Create your first AI agent to automate workspace insights and repetitive work.</p><Button className="mt-5" onClick={() => setOpen(true)}><Plus />Create agent</Button></div>}<CreateAgentDialog open={open} onOpenChange={setOpen} onCreate={(agent: Agent) => setAgents((current) => [agent, ...current])} /></div>; }
