"use client";
import * as React from "react";
import { Bot, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { agentTypes, type Agent } from "@/lib/ai-agents-data";

export function CreateAgentDialog({ open, onOpenChange, onCreate }: { open: boolean; onOpenChange: (value: boolean) => void; onCreate: (agent: Agent) => void }) { const [name, setName] = React.useState(""); const [description, setDescription] = React.useState(""); const [type, setType] = React.useState(agentTypes[0]); const reset = () => { setName(""); setDescription(""); setType(agentTypes[0]); }; if (!open) return null; const submit = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return; // TODO: Connect create-agent API
onCreate({ id: crypto.randomUUID(), name: name.trim(), description: description.trim() || "A custom FlowDesk workspace assistant.", status: "draft", type, workspace: "FlowDesk Core", instructions: "Help the team with workspace tasks and provide concise, useful recommendations.", lastActive: "Not run yet", actions: 0, icon: "chart", frequency: "Manual", permissions: "Tasks and projects" }); reset(); onOpenChange(false); }; return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button type="button" aria-label="Close dialog" onClick={() => onOpenChange(false)} className="absolute inset-0 bg-foreground/30 backdrop-blur-sm" /><form onSubmit={submit} className="relative max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-xl border bg-card p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><div><div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><Bot className="size-5" /></div><h2 className="mt-3 text-lg font-semibold">Create AI agent</h2><p className="mt-1 text-sm text-muted-foreground">Set up a local-only assistant for your workspace.</p></div><Button size="icon" variant="ghost" aria-label="Close dialog" onClick={() => onOpenChange(false)}><X /></Button></div><div className="mt-5 grid gap-4"><label className="grid gap-1.5 text-sm font-medium">Agent name<Input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Release coordinator" required /></label><label className="grid gap-1.5 text-sm font-medium">Description<Input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What does this agent help with?" /></label><label className="grid gap-1.5 text-sm font-medium">Agent type<select value={type} onChange={(event) => setType(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm">{agentTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Workspace<select className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option>FlowDesk Core</option></select></label><label className="grid gap-1.5 text-sm font-medium">Instructions<textarea className="min-h-28 rounded-md border border-input bg-background px-3 py-2 text-sm" defaultValue="You are a helpful FlowDesk workspace assistant. Provide concise, actionable recommendations." /></label></div><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit">Create agent</Button></div></form></div>; }
